name: Generate Cypress Report
on: 
  push:
    branches:
      - 'master'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
           command: npx cypress run
      - name : Uploding artifact
        uses : actions/upload-artifact@v3
        if: always()
        with :
          name: cypress-execution-report
          path : cypress\reports\html
          retention-days: 30
          
        uses : actions/upload-artifact@v3
        if: faliure()
        with:
          name: cypress-screenshots
          path: cypress/reports/screenshots

        uses : actions/upload-artifact@v3
        if: faliure()
        with:
          name: cypress-videos
          path: cypress/reports/videos
      
# - name: Deploy
#   uses: peaceiris/actions-gh-pages@v4
#   with:
#     github_token: ${{ secrets.GITHUB_TOKEN }}
#     publish_dir: ./public