name: Generate Cypress Report
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command:  npm run test:ui:magneto
      
      - name: Upload Cypress Execution Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30

      # - name: Upload Cypress Screenshots
      #   uses: actions/upload-artifact@v3
      #   if: failure()
      #   with:
      #     name: cypress-screenshots
      #     path: cypress/reports/screenshots

      # - name: Upload Cypress Videos
      #   uses: actions/upload-artifact@v3
      #   if: failure()
      #   with:
      #     name: cypress-videos
      #     path: cypress/reports/videos
      
- name: Deploy
  uses: peaceiris/actions-gh-pages@v4
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./public
